// File generated by FlutterFire CLI.
// ignore_for_file
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqfYQrW6_ZMYT-oULluqa2uZSVQFrXuU',
    appId: '1:835868431786:web:76619588777c70b3ab87d3',
    messagingSenderId: '835868431786',
    projectId: 'device-streaming-14a71d5a',
    authDomain: 'device-streaming-14a71d5a.firebaseapp.com',
    storageBucket: 'device-streaming-14a71d5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpy9cVK0-pbsWlx6f1YPYzYYxuq6HiPws',
    appId: '1:835868431786:android:971fc0c7e22587b3ab87d3',
    messagingSenderId: '835868431786',
    projectId: 'device-streaming-14a71d5a',
    storageBucket: 'device-streaming-14a71d5a.firebasestorage.app',
  );
}


